apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: weather-prod
  labels:
    app.kubernetes.io/part-of: weather-aqi-system
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 2Gi
