apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: weather-prod
  labels:
    app.kubernetes.io/name: db
    app.kubernetes.io/part-of: weather-aqi-system
    app.kubernetes.io/component: database
spec:
  type: ClusterIP # dostępny tylko wewnątrz klastra
  selector:
    app: db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
